config/routes.rb
Rails.application.routes.draw do
  get 'epicenter/feed'

  post 'epi_tweet' => 'epicenter#epi_tweet'

  get  'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get  'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'
  
  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'



  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation  :link_check, on: :create

	validates :message, presence: true
	validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}

	after_validation :apply_link, on: :create

	private 

	def link_check
      check = false
      if self.message.include? "http://" 
         check = true
      elsif self.message.include? "https://"
         check = true
       elsif self.message.include? "www."
          check = true
      else
           check = false
      end	
    
      if check == true
    	arr = self.message.split
    	index = arr.map{ |x| x.include?("http") || x.include?("www.") }.index(true)
        self.link = arr[index]
        if arr[index].length > 23
    	    arr[index] = "#{arr[index][0..20]}..."	
        end
    				
        self.message = arr.join(" ")
      end
     end

     def apply_link
		arr = self.message.split
		index = arr.map { |x| x.include?("http://") || x.include?("https://") || x.include?("www.")}.index(true)

		if index
			url = arr[index]
      if arr.map { |x| x.include?("http")}.index(true)
        arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
        else
          arr[index] = "<a href='http://#{self.link}' target='_blank'>#{url}</a>"
      end
			
		end

		self.message = arr.join(" ")
	end


end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet 
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  serialize :following, Array

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper :all

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end

end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

	before_action :authenticate_user!

  include TweetsHelper


  def feed
  	@following_tweets = Array.new

  	Tweet.order(id: :desc).each do |t|
  		if current_user.following.include?(t.user_id) || current_user.id == t.user_id
  			@following_tweets.push(t)
  		end 
      # @following_tweets = @following_tweets.order('created_at' DESC)
  	end
  end

  def show_user
  	@user = User.find(params[:id])
    # @user = User.find_by(params[:username])
  end

  def now_following
  	# We are adding the user.id of the user you want to 
  # follow to your following array.
  # and we want to make sure it's saved in there as an integer
  current_user.following.push(params[:id].to_i)
  current_user.save

  redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end

  def epi_tweet
    # @tweet = Tweet.new

    # @tweet.message = "#{params[:tweet][:message]}"
    # @tweet.user_id = "#{params[:tweet][:user_id].to_i}"

    @tweet = Tweet.create(message: params[:tweet][:message], user_id: params[:tweet][:user_id].to_i)
    @tweet = get_tagged(@tweet) #method from the helper 
    @tweet.save 

    redirect_to root_path
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
    
  end

  def all_users
    @users = User.all
  end

  def following
    @user = User.find(params[:id])
    @users = Array.new

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    @users = Array.new

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetsHelper
  
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(id: :desc)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet) #method from the helper 
    

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user_followers(user_id)
    

    count = 0
    User.all.each do |user|
      if user.following.include?(user_id)
       	count += 1
      end
    end
    return count
  end

  def tweet_count(user_id)
  	tweets = Array.new
  	tweets = Tweet.where(user_id: user_id)
  	
  	return tweets.length

  end

end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

	def get_tagged(tweet)

		message_arr = Array.new
		message_arr = tweet.message.split

    	message_arr.each_with_index do |word, index|
      	if word[0] == "#"
	        if Tag.pluck(:phrase).include?(word.downcase)
	          #save tag a veriable to use in TweetTag creation
	          tag = Tag.find_by(phrase: word.downcase)

	        else

	          tag = Tag.create(phrase: word.downcase)
	        
	        #create new instance of a Tag
	        end
        tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      	end
    end

    tweet.message = message_arr.join(" ")


    return tweet
		
	end
end

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
    
      <div class="well user-list-wells">
        <div class="row">
          
            <%= image_tag user.avatar.thumb %>
          
          
            <p>
              <% if current_user.following.include?(user.id) %>
                <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
              <% else %>
                <% if current_user.id != user.id %>
                  <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </p>
          
        </div>
        <div class="row">
          <%= link_to show_user_path(id: user.id) do %>
            <h3><%= user.name %></h3>
            <p>@<%= user.username %></p>
          <% end %>
          <p>
            <%= user.bio %>
          </p>
        </div>
      </div>
    
  <% end %>
</div>

app/views/epicenter/all_users.html.erb
<h1>List of all users</h1>

<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<div>
</div>
<!-- ******************middle column**************** -->
<div>
  <div class="well">
<h1 class="text-primary">@<%= current_user.username %>'s Twitter Feed</h1>
<p>Here is what's going on: </p>

<div class="search-tweak2">
<%= form_for Tweet.new, url: {action: 'epi_tweet'} do |f| %>
	<%= f.text_field :message, class: 'form-control search-form2' %>
	<%= f.hidden_field :user_id, value: current_user.id %><br />
	<%= f.submit 'New Tweet', class: 'btn btn-info pull-right' %>
<% end %>
</div><br />
<hr>
<% @following_tweets.each do |t| %>
<div class="media">
  <div class="media-left">
    <%= link_to image_tag t.user.avatar.thumb, class: "img-rounded" %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><strong>@<%= link_to t.user.username, show_user_path(id: t.user.id) %></strong></h4>
    <p><%= t.message.html_safe %></p>
    <p><%= time_ago_in_words(t.created_at) %> ago</p>
  </div>
</div>
<hr>
<% end %>
</div>
</div>

<!-- ******************** right column **************** -->
<div>
</div>

app/views/epicenter/followers.html.erb
<h1><%= @user.username %>'s followers'</h1>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h1><%= @user.username %> is following</h1>

<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1 class="text-info">@<%= @user.username %>'s Profile and Tweets</h1>

<p class="text-info">Username: <%= @user.name %></p>

<p class="text-info">Location: <%= @user.location %></p>
<p class="text-info">About Me: <%= @user.bio %></p>

<p><%= link_to "View Influencers", following_path(id: @user.id) %></p>
<p><%= link_to "View Followers", followers_path(id: @user.id) %></p>

<p>
    <% if current_user.following.include?(@user.id) %>
        <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
    <% else %>
        <% if current_user.id != @user.id %>
	    <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>

        <% else %>

            <%= form_for Tweet.new, url: {action: 'epi_tweet'} do |f| %>
                <%= f.text_field :message, class: 'form-control' %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit 'New Tweet', class: 'btn btn-info' %>
            <% end %>

	   <% end %>
    <% end %>
</p>

<% @user.tweets.each do |tweet| %>
    <div class="media">
        <div class="media-left">
            <%= link_to image_tag tweet.user.avatar.thumb, class: "img-rounded" %>
        </div>
        <div class="media-body">
        <h4 class="media-heading">@<%= @user.username %></h4>
	       <p><%= tweet.message.html_safe %></p>
        </div>
    </div>
    <hr>
    
<% end %>



    
  
  

app/views/epicenter/tag_tweets.html.erb
<div class='col-md-3'>
</div>

<div class='col-md-6'>
<div>
    <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
  <!-- a place for current user stats -->
  <div>
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
        <p> 
	    <%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
	    • <%= time_ago_in_words(tweet.created_at) %>
        </p>
	<p>
	    <%= tweet.message.html_safe %>
	</p>
    <% end %>
   </div>
</div>
</div>
<div class='col-md-3'>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictwit</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    <!-- <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'> -->
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>


    <div class="container-full" id="wrapper">
<!-- *********** new navbar **************** -->
      <nav class="topnav" id="myTopnav">
        <div class="container-fluid">
          <ul class="nav navbar-nav">
            <li><%= link_to "Pictwit", root_path %></li>
            <li><%= link_to "All Tweets", tweets_path %></li>
          </ul>
            

          
          </ul>
          <ul class="nav navbar-nav navbar-right">
              
        
                <li><%= link_to "Log In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %> </li>
            
              </ul> 
        </div>
      </nav>
<!-- ******** end navbar ********** -->


    <!-- ************************ navbar section ************************************-->
  <div class="container1">
  <nav class="navbar topnav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <li class="nav navbar-nav">
        
      </li>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Pictwit", root_path %></li>
          <li><%= link_to "All Tweets", tweets_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>

            <li><%= link_to "Compose New Tweet", root_path %></li>
            <li><%= link_to "My Page", show_user_path(id: current_user) %></li>
            <li><%= link_to "All Users", all_users_path %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
                <% end %> 
                @<%= current_user.username %></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    
  </nav>
<!-- ************************navbar end******************************** -->


  	 <!-- <div class="container1"> -->
      
          <% if user_signed_in? %>
              <div class='col-md-3'>
                      <div class="well">


                  <h2><%= image_tag current_user.avatar.thumb, :class => 'img-thumbnail center-block' %></h2><br />
                  <h4 class="text-info text-center">@<%= current_user.username %></h4>
                  <h4 class="text-info text-center">Wreckin': <%= current_user.location %></h4>
                  <h4 class="text-info text-center">About: <%= current_user.bio %></h4>
                  <p class="text-info text-center">Following: <%= link_to current_user.following.length, following_path(id: current_user.id) %> </p>
                  <p class="text-info text-center">Followers: <%= link_to current_user_followers(current_user.id) %> </p>
                  <p class="text-info text-center">Tweets: <%= link_to tweet_count(current_user.id), show_user_path(id: current_user.id) %> </p>

          <% end %> 
        
        
      </div>
      </div>
      <div class='col-md-9'>
        <!-- <div class="well"> -->
    	<%= yield %>
        <!-- </div> -->
      </div>
      <!-- <div class='col-md-3'> -->
        <!-- <div class='well'> -->
        <!-- </div> -->
      <!-- </div> -->
	   <!-- </div> -->



<!-- ******************************** scripts ************************** -->
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
    <%= form.text_field :message, id: :tweet_message, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<!-- <div class="container1"> -->


<!-- ************************ left column well ************************ -->  
      

      



<!-- ************************ middle column feed well ************************-->
      <div>
        <div class="well">
         <p id="notice"><%= notice %></p>

          <h1>All Posts</h1>


          <% @tweets.each do |tweet| %>
          <div class="media">
            <!-- <img class="d-flex mr-3" src="..." alt="placeholder image"> -->

            <div class="media-body">
              <h5 class="mt-0"><%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></h5>
              <%= tweet.message.html_safe %>
              <%= image_tag tweet.user.avatar.thumb, class: "rounded" %>
            </div>
            
<!-- version two - created at -->
            <span>
              <%= time_ago_in_words(tweet.created_at) %> ago
            </span>
            
            <%= link_to 'Show', tweet %> <%= link_to 'Edit', edit_tweet_path(tweet) %> <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
            <hr>
          </div>
          <% end %>
          <!-- <table>
            <thead>
              <tr>
                <th>Message </th>
                <th>User</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @tweets.each do |tweet| %>
                <tr>
                  <td><%= tweet.message %></td>
                  <td><%= tweet.user_id %></td>
                  <td><%= link_to 'Show', tweet %></td>
                  <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
                  <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table> -->
          <hr>

         <%= link_to 'New Tweet', new_tweet_path %>
        </div>
      </div>
  <!-- ************************ right column follow well ************************-->    
<!-- </div> -->

app/views/tweets/new.html.erb
<div class="container1">
<div class="text-primary h2">New Post

<%= render 'form', tweet: @tweet %>

</div>

<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>User:</strong>
    <%= link_to @tweet.user.username, 
       show_user_path(id: @tweet.user.id) %>
</p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %> <%= image_tag @tweet.user.avatar.thumb %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>